### ISSUE TITLE
Question about file extension

### ISSUE THREAD

**Issue by simon-mo** [strymon-system/ds2#2]
Hi, 

thank you for releasing the code! I'm having trouble running some of the experiments. In particular, the online `manager` is expecting to listening from a metric repository folder containing files with certain extensions. However, the [patch](https://github.com/strymon-system/ds2/blob/9827dea75aa1282e5893f97e4ffb0fba246e6621/flink-instrumentation/ds2.patch#L382) seems to be only writing to a file without any extensions. 

Is this an issue of my configuration? Right now, I'm able to produce the following files in `$HOME/rates` folder:
```
'Operator 1 -> Operator 2-2-5'  'Sink: Sink-1-24'  'Source: Source-1-2'
'Sink: Sink-1-0'                'Sink: Sink-1-25'  'Source: Source-1-3'
...
```

And they are formatted correctly in csv form
```
Sink: Sink,1,1,1596485970170338,26923.039268476547,0.0,2.132279033470391,0.0
```

However, even when I put the following to the toml file
```
metrics_repo = "/home/ubuntu/rates"
file_extension = ""
```

The `manager` seems to hang forever after kicking off the job. It will print out 
```
Submitted Flink job with id: 2aee4606a4cc421ed35757a0707fd398
```
and never print out anything again.

**Comment by jliagouris** [comment]
cc @vasia 

Flink's patch should now output ".log" files. Can you retry?
