### ISSUE TITLE
Implementation of MetricsManager for Flink

### ISSUE THREAD

**Issue by ZanZong** [strymon-system/ds2#3]
Hello, I'm trying to build ds2 and adapting it to my scenario. Everything goes well when following the steps in readme. 
I found examples of *rates*  for each operator instance and epoch. **I would like to know how the *true_processing_rate,true_output_rate,observed_processing_rate and observed_output_rate* are measured.** In my previous works, the [metric system of flink](https://ci.apache.org/projects/flink/flink-docs-release-1.7/monitoring/metrics.html) was used to get metrics information, but it seems too naive now.
Please give some hints for the implementation of MetricsManager. Should I insert stubs to flink's source code?
thanks!

**Comment by ZanZong** [comment]
oh! I have found the patch files. Thanks for sharing!

**Comment by vasia** [comment]
Hi @ZanZong,

Great that you found the patch files. Let us know if you run into any issues.

-V.
